import "./globals.css";

export const metadata = {
  title: "Tachi Galletas",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main className="font-teachers">
          {children}
        </main>
      </body>
    </html>
  );
}
